export default {
  UPDATE_TITLE_FILTER: 'UPDATE_TITLE_FILTER',
  UPDATE_FILTER_VALUE: 'UPDATE_FILTER_VALUE',
  SET_RESULTS: 'SET_FILTER_RESULTS',
  UPDATE_ERROR: 'UPDATE_FILTER_ERROR',
  CLEAR_FILTERS: 'CLEAR_SEARCH_FILTERS',
};
